create database auction;

use auction;

CREATE TABLE AUCTION.AUCTION_HOUSE (
	AUCTION_HOUSE_ID INT AUTO_INCREMENT PRIMARY KEY,
	AUCTION_HOUSE_NAME VARCHAR(50),
	ADDRESS VARCHAR(255)
);

CREATE TABLE AUCTION.USER_INFO (
	USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(40) NOT NULL,
    LAST_NAME VARCHAR(40) ,
    EMAIL VARCHAR(40) NOT NULL,
    COUNTRY_CODE VARCHAR(10) NOT NULL,
	CONTACT_NO CHAR(10) NOT NULL,
    USER_STATUS VARCHAR(40) NOT NULL,
    REGISTRATION_DATE TIMESTAMP NOT NULL

);

CREATE TABLE AUCTION.ITEM_BID (
	ITEM_BID_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    BID_AMOUNT DECIMAL(12,6) NOT NULL,
    BID_STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES AUCTION.USER_INFO(USER_ID)
);


CREATE TABLE AUCTION.AUCTION_ITEM (
	AUCTION_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    OWNER_ID INT NOT NULL,
    FOREIGN KEY(OWNER_ID) REFERENCES AUCTION.USER_INFO(USER_ID)
);



CREATE TABLE AUCTION.AUCTION_DATA(
	AUCTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUCTION_HOUSE_ID INT NOT NULL,
    AUCTION_ITEM_ID INT NOT NULL,
    AUCTION_STATUS VARCHAR(40) NOT NULL,
    STEP_RATE DECIMAL(10,6) NOT NULL,
    MIN_BID_PRICE DECIMAL(10,6) NOT NULL,
    UPDATED_ON TIMESTAMP,
    START_DATE  TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    COMMISSION DECIMAL(10,6) NOT NULL,
    FOREIGN KEY(AUCTION_HOUSE_ID) REFERENCES AUCTION.AUCTION_HOUSE(AUCTION_HOUSE_ID),
    FOREIGN KEY(AUCTION_ITEM_ID) REFERENCES AUCTION.AUCTION_ITEM(AUCTION_ITEM_ID)
);



ALTER table AUCTION.ITEM_BID
ADD COLUMN AUCTION_ID INT NOT NULL,
  ADD FOREIGN KEY auction_id(AUCTION_ID) REFERENCES AUCTION.AUCTION_DATA(AUCTION_ID) ;




